### PR TITLE
added autocompletion for days of week, "this week" and "next week"

### PR DESCRIPTION
**Pull request by np-trivial**

### CODE REVIEW

**Comment by usernamehw** [comment]
Hmmm... this is not good.

With today being `2022-04-25`

|  Calendar       |  Current implementation         |
| ------------- |-------------|
|       |  |

Multiple things:

- There are probably people with the Sunday as the first day of the week
- Today is Monday, but this implementation made `SET_DUE_MON` for the next week, which is unexpected
- No need to abbreviate completion: `SET_DUE_MONDAY` easier to read
- `SET_DUE_NEXTWEEK` should be named `SET_DUE_NEXT_WEEK`
- I would expect `THIS_WEEK` & `NEXT_WEEK` to be due on any day of that week
- Week ending on Friday makes no sense


---

To make it work:

New type of due date: week `{due:week|2022-26}` https://day.js.org/docs/en/plugin/week-of-year

This due date is due (highlighted in blue) on any day of that week (`2022-04-25`, `2022-04-26`, `2022-04-27`, `2022-04-28`, `2022-04-29`, `2022-04-29`, `2022-04-30`, `2022-05-01`, `2022-05-02`)

For the weekday completions - if the day is the same is current (Monday - Monday) => it should pick today's date.

**Comment by np-trivial** [comment]
FYI, this is working as I intended. So, this is a conversation about design decisions.

Also, my perspective is coming from a business context, which is where I use it. I am guessing (unsure, though), that most users of this plugin are also using it in a business or school context. More on this below, inline.

> No need to abbreviate completion: SET_DUE_MONDAY is easier to read

> SET_DUE_NEXTWEEK should be named SET_DUE_NEXT_WEEK

I have no qualms with those and can change it.

> There are probably people with the Sunday as the first day of the week
> I would expect THIS_WEEK & NEXT_WEEK to be due on any day of that week
> Week ending on Friday makes no sense

In my experience (North America) business context and school context, if somebody says something is due "this week", I would expect that to mean "by the end of this week". Typical North America and Europe business/school schedules run Monday - Friday. So I interpret "this week" to mean "end of the week", which would translate to "Friday" in most contexts.

> Today is Monday, but this implementation made SET_DUE_MON for the next week, which is unexpected

If somebody told me a thing was due to them on a day of the week, and today was also that day of the week, I would generally interpret that to mean "one week from today". If the requestor meant "today", I presume they would say "today", not e.g. "Monday" when today is Monday.

> New type of due date: week {due:week|2022-18}

>There is already a method that is used when running Todo Md: Set due date command. You can feed it monday helpCreateDueDate('monday') and get 2022-04-25 return value (for the completion item). 

The intent of these autocompletes is to save time, both typing and thinking. With the autocomplete I propose, I can insert the desired due date in 3-4 keystrokes. The existing solutions require many more keystrokes and time.

> This due date is due (highlighted in blue) on any day of that week

This is an unusual perspective to me. "Due" seems like an instant of time. There is rarely any difference between moments before a deadline versus days before a deadline. Typically we generalize this to a date, but even this plugin allows granularity to the second. Sometimes a deadline has a specific time, e.g. "Friday at 8 AM". It doesn't seem like adding a range of dates that something is in a "due now" state helps much.

**Comment by usernamehw** [comment]
> In my experience (North America) business context and school context, if somebody says something is due "this week", I would expect that to mean "by the end of this week". Typical North America and Europe business/school schedules run Monday - Friday. So I interpret "this week" to mean "end of the week", which would translate to "Friday" in most contexts.

I'm too lazy to argue or create a new due type. We can agree that this week ends with either Friday or Sunday (it must be a user setting).

> If somebody told me a thing was due to them on a day of the week, and today was also that day of the week, I would generally interpret that to mean "one week from today". If the requestor meant "today", I presume they would say "today", not e.g. "Monday" when today is Monday.

I've almost never used todo apps. Here's an example of a popular app (that's free and doesn't require downloading): https://todoist.com/ . In this app writing due date as `"tuesday"` today (which is Tuesday) sets due date to ... today.

> The intent of these autocompletes is to save time, both typing and thinking. With the autocomplete I propose, I can insert the desired due date in 3-4 keystrokes. The existing solutions require many more keystrokes and time.

I'm not saying to use that command. I'm saying to use that existing function to generate the completion item's date.

---

That Todoist app also seems to not have `THIS_WEEK` item and `NEXT_WEEK` by default uses next week's Monday (says it can be changed in settings idk) https://todoist.com/help/articles/due-dates-and-times

**Comment by usernamehw** [comment]
I've added autocomplete items `SET_DUE_THIS_WEEK` & `SET_DUE_NEXT_WEEK` with settings (Friday default):

```ts
/**
 * Week day when using set due date command or suggest `SET_DUE_THIS_WEEK`.
 */
setDueDateThisWeekDay: 'Friday' | 'Sunday';
/**
 * Week day when using set due date command or suggest `SET_DUE_NEXT_WEEK`.
 */
setDueDateNextWeekDay: 'Friday' | 'Monday' | 'Sunday';
```

And completions for weekdays `SET_DUE_MONDAY`, ... which works the same way as `Set due date` command.

**Comment by np-trivial** [comment]
Thank you!

**Pull request closed without merging**
