### PR TITLE
Fix for Issue #54

### PR DESCRIPTION
**Pull request by dustinsterk**
I worked on this last evening and believe this is the bug causing #54

### CODE REVIEW

**Comment by usernamehw** [comment]
No, this is going to duplicate tasks and maybe break other features.

This piece:

https://github.com/usernamehw/vscode-todo-md/blob/3282e60104aaa1ad3b41b15ad08abfc707004806/src/treeViewProviders/treeViews.ts#L149

must use `filterItems` and wherever possible `filterItems` should be used.

https://github.com/usernamehw/vscode-todo-md/blob/3282e60104aaa1ad3b41b15ad08abfc707004806/src/filter.ts#L12

Then `filterItems` should implement the logic of recursively walking through `subtasks` to see if any of the children match.

**Comment by dustinsterk** [comment]
Ah yes good point.  Updated per your suggestion.

**Comment by dustinsterk** [comment]
Re-used your recursive function to check all subtask children for a 'due/overdue' item.  Please review.

**Comment by usernamehw** [comment]
Thanks. I might try to exclude nested items that don't match the filter in the future (if it's easy).

**Comment by dustinsterk** [comment]
Awesome!  Thank you!

**Pull request merged**
